### ISSUE TITLE
It doesn't build on nixos zig 0.15.2

### ISSUE THREAD

**Issue by dzorya** [PrajwalCH/zig-arg#49]
How to replicate bug:
```
nixos:~/repos> git clone https://github.com/prajwalch/yazap.git
Cloning into 'yazap'...
remote: Enumerating objects: 4781, done.
remote: Counting objects: 100% (453/453), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 4781 (delta 400), reused 389 (delta 376), pack-reused 4328 (from 2)
Receiving objects: 100% (4781/4781), 18.06 MiB | 6.71 MiB/s, done.
Resolving deltas: 100% (3464/3464), done.
nixos:~/repos> cd yazap/
nixos:~/repos/yazap> zig version
0.15.2
nixos:~/repos/yazap> zig build
build.zig:29:28: error: root source file struct 'Io' has no member named 'Threaded'
    var threaded_io: std.Io.Threaded = .init_single_threaded;
                     ~~~~~~^~~~~~~~~
/nix/store/3dp12p97srhxnhhv2xq90xpfilnjdjk5-zig-0.15.2/lib/zig/std/Io.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
referenced by:
    build: build.zig:10:17
    runBuild__anon_23416: /nix/store/3dp12p97srhxnhhv2xq90xpfilnjdjk5-zig-0.15.2/lib/zig/std/Build.zig:2214:33
    6 reference(s) hidden; use '-freference-trace=8' to see all references
nixos:~/repos/yazap>
```
In zig 0.15.2 https://codeberg.org/ziglang/zig/src/tag/0.15.2/lib/std/Io.zig doesn't have Threaded
It appears only in master https://codeberg.org/ziglang/zig/blame/branch/master/lib/std/Io.zig

<img width="1025" height="1181" alt="Image" src="https://github.com/user-attachments/assets/ae0116ee-2e65-4447-8a71-2adaf2045851" />
